-- Generated by Fifth compiler
-- ColorFORTH to SPARK
--
-- DO NOT EDIT - Generated code

pragma SPARK_Mode (On);

package Countdown is

   --  Stack configuration
   Stack_Size : constant := 256;
   type Stack_Index is range 0 .. Stack_Size;
   subtype Valid_Stack_Index is Stack_Index range 1 .. Stack_Size;

   --  Cell is a 32-bit signed integer
   type Cell is range -(2**31) .. (2**31 - 1);

   --  Stack storage
   type Stack_Array is array (Valid_Stack_Index) of Cell;

   --  Stack with pointer
   type Stack_Type is record
      Data : Stack_Array;
      SP   : Stack_Index;
   end record;

   --  Initialize stack
   procedure Init (S : out Stack_Type)
     with Post => S.SP = 0;

   procedure Countdown (S : in out Stack_Type)
     with Pre => S.SP >= 1;

   procedure Abs (S : in out Stack_Type)
     with Pre => S.SP >= 1;

   procedure Max2 (S : in out Stack_Type)
     with Pre => S.SP >= 2;

   procedure Test (S : in out Stack_Type)
     with Pre => S.SP >= 0;

end Countdown;
