-- Generated by Fifth compiler
-- ColorFORTH to SPARK
--
-- DO NOT EDIT - Generated code

pragma SPARK_Mode (On);
with Ada.Text_IO; use Ada.Text_IO;

package body Countdown is

   procedure Init (S : out Stack_Type) is
   begin
      S.Data := (others => 0);
      S.SP := 0;
   end Init;

   procedure Countdown (S : in out Stack_Type) is
      Loop_Index : Cell := 0;
      Loop_Limit : Cell := 0;
   begin
      Loop_Limit := S.Data (S.SP);
      S.SP := S.SP - 1;
      Loop_Index := 0;
      while Loop_Index < Loop_Limit loop
         S.SP := S.SP + 1;
         S.Data (S.SP) := Loop_Index;
         Put (Cell'Image (S.Data (S.SP)));
         S.SP := S.SP - 1;
         Put (' ');
         Loop_Index := Loop_Index + 1;
      end loop;
      New_Line;
   end Countdown;

   procedure Abs (S : in out Stack_Type) is
   begin
      S.SP := S.SP + 1;
      S.Data (S.SP) := S.Data (S.SP - 1);
      if S.Data (S.SP) < 0 then
         S.Data (S.SP) := -1;
      else
         S.Data (S.SP) := 0;
      end if;
      declare
         If_Flag : constant Cell := S.Data (S.SP);
      begin
         S.SP := S.SP - 1;
         if If_Flag /= 0 then
            S.Data (S.SP) := -S.Data (S.SP);
         end if;
      end;
   end Abs;

   procedure Max2 (S : in out Stack_Type) is
   begin
      S.SP := S.SP + 2;
      S.Data (S.SP - 1) := S.Data (S.SP - 3);
      S.Data (S.SP) := S.Data (S.SP - 2);
      if S.Data (S.SP - 1) < S.Data (S.SP) then
         S.Data (S.SP - 1) := -1;
      else
         S.Data (S.SP - 1) := 0;
      end if;
      S.SP := S.SP - 1;
      declare
         If_Flag : constant Cell := S.Data (S.SP);
      begin
         S.SP := S.SP - 1;
         if If_Flag /= 0 then
            declare
               Temp : constant Cell := S.Data (S.SP);
            begin
               S.Data (S.SP) := S.Data (S.SP - 1);
               S.Data (S.SP - 1) := Temp;
            end;
         end if;
      end;
      S.SP := S.SP - 1;
   end Max2;

   procedure Test (S : in out Stack_Type) is
   begin
      S.SP := S.SP + 1;
      S.Data (S.SP) := 10;
      Countdown (S);
   end Test;

end Countdown;
