-- Generated by Fifth compiler
-- ColorFORTH to SPARK
--
-- DO NOT EDIT - Generated code

pragma SPARK_Mode (On);
with Ada.Text_IO; use Ada.Text_IO;

package body Square is

   procedure Init (S : out Stack_Type) is
   begin
      S.Data := (others => 0);
      S.SP := 0;
   end Init;

   procedure Square (S : in out Stack_Type) is
   begin
      S.SP := S.SP + 1;
      S.Data (S.SP) := S.Data (S.SP - 1);
      S.Data (S.SP - 1) := S.Data (S.SP - 1) * S.Data (S.SP);
      S.SP := S.SP - 1;
   end Square;

   procedure Test (S : in out Stack_Type) is
   begin
      S.SP := S.SP + 1;
      S.Data (S.SP) := 5;
      Square (S);
      Put (Cell'Image (S.Data (S.SP)));
      S.SP := S.SP - 1;
      New_Line;
   end Test;

end Square;
